apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: portal
  namespace: f6e00d-tools
spec:
  params:
    - name: helmDir
      type: string
    - name: helmValues
      type: string
    - name: helmRelease
      type: string
    - name: helmImage
      type: string
    - name: imageRegistry
      type: string
    - name: imageRegistryUser
      type: string
    - name: imageRegistryPass
      type: string
    - name: imageUrl
      type: string
    - name: repoUrl
      type: string
    - name: branchName
      type: string
    - name: pathToContext
      type: string
    - name: dockerfile
      type: string
    - name: buildahImage
      type: string
    - name: deploymentName
      type: string

  workspaces:
    - name: shared-data
      description: Stores cloned source repository

  tasks:
    # ---------------------------------------------------
    # Clone Git Repository
    # ---------------------------------------------------
    - name: git-clone
      params:
        - name: url
          value: $(params.repoUrl)
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.branchName)
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data

    # ---------------------------------------------------
    # Generate Commit ID
    # ---------------------------------------------------
    - name: generate-id
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: generate-id
      workspaces:
        - name: source
          workspace: shared-data

    # ---------------------------------------------------
    # Set VITE Secret & Namespace dynamically based on branch
    # ---------------------------------------------------
    - name: set-vite-secret
      runAfter:
        - generate-id
      params:
        - name: branchName
          value: $(params.branchName)
      taskSpec:
        params:
          - name: branchName
            type: string
        results:
          - name: secretName
            type: string
          - name: namespace
            type: string
          - name: imageTag
            type: string
        steps:
          - name: set-secret-and-namespace
            image: registry.access.redhat.com/ubi9/ubi-minimal
            env:
              - name: BRANCH_NAME
                value: $(params.branchName)
              - name: SECRET_NAME_PATH
                value: $(results.secretName.path)
              - name: NAMESPACE_PATH
                value: $(results.namespace.path)
              - name: IMAGE_TAG_PATH
                value: $(results.imageTag.path)
            script: |
              #!/bin/bash
              set -euxo pipefail

              echo "DEBUG: branchName param = '${BRANCH_NAME}'"

              # Clear any previous values to avoid stale results
              : > "${SECRET_NAME_PATH}"
              : > "${NAMESPACE_PATH}"
              : > "${IMAGE_TAG_PATH}"

              case "${BRANCH_NAME}" in
                dev|develop)
                  echo -n "vite-dev" > "${SECRET_NAME_PATH}"
                  echo -n "f6e00d-dev" > "${NAMESPACE_PATH}"
                  echo -n "dev" > "${IMAGE_TAG_PATH}"
                  ;;
                test)
                  echo -n "vite-test" > "${SECRET_NAME_PATH}"
                  echo -n "f6e00d-test" > "${NAMESPACE_PATH}"
                  echo -n "test" > "${IMAGE_TAG_PATH}"
                  ;;
                main|prod)
                  echo -n "vite-prod" > "${SECRET_NAME_PATH}"
                  echo -n "f6e00d-prod" > "${NAMESPACE_PATH}"
                  echo -n "prod" > "${IMAGE_TAG_PATH}"
                  ;;
                *)
                  echo "ERROR: Unknown branch '${BRANCH_NAME}'"
                  exit 1
                  ;;
              esac

              echo "DEBUG: resolved secretName = '$(cat "${SECRET_NAME_PATH}")'"
              echo "DEBUG: resolved namespace  = '$(cat "${NAMESPACE_PATH}")'"
              echo "DEBUG: resolved imageTag   = '$(cat "${IMAGE_TAG_PATH}")'"

    # ---------------------------------------------------
    # Build Image With Buildah (uses dynamic secret & branch tag)
    # ---------------------------------------------------
    - name: buildah
      runAfter:
        - set-vite-secret
      params:
        - name: IMAGE
          value: $(params.imageUrl)
        - name: IMAGE_TAG
          value: $(tasks.set-vite-secret.results.imageTag)
        - name: IMAGE_REGISTRY
          value: $(params.imageRegistry)
        - name: IMAGE_REGISTRY_USER
          value: $(params.imageRegistryUser)
        - name: IMAGE_REGISTRY_PASS
          value: $(params.imageRegistryPass)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.pathToContext)
        - name: BUILDAH_IMAGE
          value: $(params.buildahImage)
        - name: VITE_SECRET_NAME
          value: $(tasks.set-vite-secret.results.secretName)
        - name: BRANCH_NAME
          value: $(params.branchName)
      taskRef:
        name: buildah-vite
        kind: Task
      workspaces:
        - name: source
          workspace: shared-data

    # ---------------------------------------------------
    # Helm Deploy
    # ---------------------------------------------------
    - name: helm-deploy
      runAfter:
        - buildah
      params:
        - name: HELM_DIR
          value: $(params.helmDir)
        - name: HELM_VALUES
          value: $(params.helmValues)
        - name: HELM_RELEASE
          value: $(params.helmRelease)
        - name: HELM_IMAGE
          value: $(params.helmImage)
        - name: IMAGE
          value: $(params.imageUrl)
        - name: IMAGE_TAG
          value: $(tasks.set-vite-secret.results.imageTag)
        - name: NAMESPACE
          value: $(tasks.set-vite-secret.results.namespace)
      taskRef:
        kind: Task
        name: helm-deploy
      workspaces:
        - name: source
          workspace: shared-data

    # ---------------------------------------------------
    # Deployment Reroll (uses dynamic namespace)
    # ---------------------------------------------------
    - name: reroll-deployment
      runAfter:
        - helm-deploy
      params:
        - name: deploymentName
          value: $(params.deploymentName)
        - name: namespace
          value: $(tasks.set-vite-secret.results.namespace)
      taskRef:
        kind: Task
        name: reroll-deployment
