apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah-vite
  namespace: f6e00d-tools
spec:
  params:
    - name: IMAGE
      type: string
    - name: VITE_SECRET_NAME
      type: string
    - name: BRANCH_NAME
      type: string
    - name: BUILDAH_IMAGE
      type: string
    - name: STORAGE_DRIVER
      type: string
      default: overlay
    - name: DOCKERFILE
      type: string
      default: ./Dockerfile
    - name: CONTEXT
      type: string
      default: .
    - name: IMAGE_REGISTRY
      type: string
      default: docker.io
    - name: IMAGE_REGISTRY_USER
      type: string
      default: image-registry-username
    - name: IMAGE_REGISTRY_PASS
      type: string
      default: image-registry-password
  workspaces:
    - name: source
  volumes:
    - name: varlibcontainers
      emptyDir: {}
  steps:
    - name: build
      image: $(params.BUILDAH_IMAGE)
      script: |
        #!/usr/bin/env bash
        set -ex

        # Build the container image using branch name as the tag
        buildah --storage-driver=$(params.STORAGE_DRIVER) bud --no-cache \
          --build-arg VITE_API_URL=$VITE_API_URL \
          --build-arg VITE_BCSC_CLIENT_ID=$VITE_BCSC_CLIENT_ID \
          --build-arg VITE_KILN_URL=$VITE_KILN_URL \
          --build-arg VITE_BCSC_AUTHORITY=$VITE_BCSC_AUTHORITY \
          -f $(params.DOCKERFILE) \
          -t $(params.IMAGE_REGISTRY)/$(params.IMAGE):$(params.BRANCH_NAME) \
          --isolation chroot $(params.CONTEXT)
      workingDir: $(workspaces.source.path)
      securityContext:
        capabilities:
          add: [SETFCAP]
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      env:
        - name: VITE_API_URL
          valueFrom:
            secretKeyRef:
              name: $(params.VITE_SECRET_NAME)
              key: VITE_API_URL
        - name: VITE_BCSC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: $(params.VITE_SECRET_NAME)
              key: VITE_BCSC_CLIENT_ID
        - name: VITE_BCSC_AUTHORITY
          valueFrom:
            secretKeyRef:
              name: $(params.VITE_SECRET_NAME)
              key: VITE_BCSC_AUTHORITY
        - name: VITE_KILN_URL
          valueFrom:
            secretKeyRef:
              name: $(params.VITE_SECRET_NAME)
              key: VITE_KILN_URL

    - name: push
      image: $(params.BUILDAH_IMAGE)
      script: |
        buildah --storage-driver=$(params.STORAGE_DRIVER) push $(params.IMAGE_REGISTRY)/$(params.IMAGE):$(params.BRANCH_NAME)
      workingDir: $(workspaces.source.path)
      securityContext:
        capabilities:
          add: [SETFCAP]
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers

    - name: trivy-scan
      image: docker.io/aquasec/trivy
      script: |
        trivy image $(params.IMAGE_REGISTRY)/$(params.IMAGE):$(params.BRANCH_NAME)
      workingDir: $(workspaces.source.path)
