apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah-vite
  namespace: f6e00d-tools
spec:
  params:
    - name: IMAGE
      type: string
    - name: IMAGE_TAG
      type: string
    - name: BUILDAH_IMAGE
      type: string
    - name: STORAGE_DRIVER
      type: string
      default: overlay
    - name: DOCKERFILE
      type: string
      default: ./Dockerfile
    - name: CONTEXT
      type: string
      default: .
    - name: IMAGE_REGISTRY
      type: string
      default: docker.io
    - name: IMAGE_REGISTRY_USER
      type: string
      default: image-registry-username
    - name: IMAGE_REGISTRY_PASS
      type: string
      default: image-registry-password
  workspaces:
    - name: source
  volumes:
    - name: varlibcontainers
      emptyDir: {}
  steps:
    - name: build
      image: $(params.BUILDAH_IMAGE)
      script: |
        #!/usr/bin/env bash
        set -x

        # Login to the registry using credentials from secrets
        buildah login -u $IMAGE_REGISTRY_USER -p $IMAGE_REGISTRY_PASS $(params.IMAGE_REGISTRY)

        buildah --storage-driver=$(params.STORAGE_DRIVER) bud --no-cache \
          --build-arg VITE_API_URL=$VITE_API_URL \
          --build-arg VITE_BCSC_CLIENT_ID=$VITE_BCSC_CLIENT_ID \
          --build-arg VITE_KILN_URL=$VITE_KILN_URL \
          --build-arg VITE_BCSC_AUTHORITY=$VITE_BCSC_AUTHORITY \
          -f $(params.DOCKERFILE) -t $(params.IMAGE_REGISTRY)/$(params.IMAGE):latest \
          --isolation chroot $(params.CONTEXT)

        # Push the image
        buildah --storage-driver=$(params.STORAGE_DRIVER) push $(params.IMAGE_REGISTRY)/$(params.IMAGE):latest

      workingDir: $(workspaces.source.path)
      securityContext:
        capabilities:
          add: [SETFCAP]
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      env:
        - name: VITE_API_URL
          valueFrom:
            secretKeyRef:
              key: VITE_API_URL
              name: vite-secrets
        - name: VITE_BCSC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: VITE_BCSC_CLIENT_ID
              name: vite-secrets
        - name: VITE_BCSC_AUTHORITY
          valueFrom:
            secretKeyRef:
              key: VITE_BCSC_AUTHORITY
              name: vite-secrets
        - name: VITE_KILN_URL
          valueFrom:
            secretKeyRef:
              key: VITE_KILN_URL
              name: vite-secrets
    - name: trivy-scan
      image: docker.io/aquasec/trivy
      script: |
        trivy image $(params.IMAGE_REGISTRY)/$(params.IMAGE):latest
      workingDir: $(workspaces.source.path)
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
    - name: push
      image: $(params.BUILDAH_IMAGE)
      script: |
        #!/usr/bin/env bash
        set -x
        buildah login -u $IMAGE_REGISTRY_USER -p $IMAGE_REGISTRY_PASS $(params.IMAGE_REGISTRY)
        buildah --storage-driver=$(params.STORAGE_DRIVER) push $(params.IMAGE_REGISTRY)/$(params.IMAGE):latest
      workingDir: $(workspaces.source.path)
      securityContext:
        capabilities:
          add: [SETFCAP]
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      env:
        - name: IMAGE_REGISTRY_USER
          valueFrom:
            secretKeyRef:
              name: $(params.IMAGE_REGISTRY_USER)
              key: $(params.IMAGE_REGISTRY_USER)
        - name: IMAGE_REGISTRY_PASS
          valueFrom:
            secretKeyRef:
              name: $(params.IMAGE_REGISTRY_PASS)
              key: $(params.IMAGE_REGISTRY_PASS)

