kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.portal.podlabel }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.portal.podlabel }}
spec:
  {{- if not (hasSuffix "-prod" .Release.Namespace) }}
  replicas: {{ .Values.portal.replicas | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.portal.podlabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.portal.podlabel }}
    spec:
      containers:
        - name: {{ .Values.portal.podlabel }}
          image: '{{ .Values.portal.image }}:{{ if hasSuffix "-prod" .Release.Namespace }}main{{ else }}{{ (last (splitList "-" .Release.Namespace)) }}{{ end }}'
          ports:
            - containerPort: {{ .Values.portal.port }}
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.portal.resources.limits.cpu | quote }}
              memory: {{ .Values.portal.resources.limits.memory }}
            requests:
              cpu: {{ .Values.portal.resources.requests.cpu | quote }}
              memory: {{ .Values.portal.resources.requests.memory }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
