kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: caregiver-portal
  namespace: {{.Release.Namespace}}
spec:
  host: caregiver-portal-{{.Release.Namespace}}.apps.gold.devops.gov.bc.ca
  to:
    kind: Service
    name: caregiver-portal-service
    weight: 100
  port:
    targetPort: https
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
