kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: react-app
  namespace: {{.Release.Namespace}}
spec:
  host: react-app-{{.Release.Namespace}}.apps.gold.devops.gov.bc.ca
  to:
    kind: Service
    name: react-app-service
    weight: 100
  port:
    targetPort: https
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
