kind: Service
apiVersion: v1
metadata:
  name: react-app-service
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: react-app
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  sessionAffinity: None
  internalTrafficPolicy: Cluster