kind: Service
apiVersion: v1
metadata:
  name: caregiver-portal-service
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: caregiver-portal
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  sessionAffinity: None
  internalTrafficPolicy: Cluster