apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: caregiver-build-push-image-trigger
  namespace: f6e00d-tools
  annotations:
    meta.helm.sh/release-name: pipelines
    meta.helm.sh/release-namespace: f6e00d-tools
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  serviceAccountName: pipeline
  namespaceSelector: {}
  resources: {}
  triggers:
    - name: caregiver-github-listener
      triggerRef: caregiver-github-trigger
      